#!/usr/bin/env bash

set -e

dir=$(dirname "${BASH_SOURCE[0]}")

echo "Make apidoc"
bash "$dir/../shortcuts/apidoc"

echo "Build jwt keys"
bash "$dir/../scripts/prepare_jwt_keys"

echo "Run tests"
bash "$dir/../shortcuts/run_tests"

export COMPOSE_FILE=docker/docker-compose.yml:docker/docker-compose.prod.yml
docker-compose build --force-rm
# Spooky bash hack for getting all images built by docker-compose
images=$(docker-compose config | grep -o 'image:\s*registry.*' | cut -d" " -f2)
for image in $images; do
    echo "pushing image: $image"
    docker push $image
done
