#!/usr/bin/env bash

set -e

# Starts test suite
#
# Usage:  test [<suite>] [<option>]
#
# Examples:
#     run_tests                 - starts all tests suites
#     run_tests unit            - starts unit test suite
#     run_tests u - you may run suite for part of tests


suite=$(echo "$1" | awk '{print tolower($0)}')
coverage=$2

run_unit_tests=false
# Normalize input
if [[ "unit" == "$suite"* ]]; then
  run_unit_tests=true
fi

if [[ true == "$run_unit_tests" ]]; then
    echo "Run Unit Test Suite"

    docker-compose run --no-deps --rm php codecept run unit $coverage
fi
